{
  "openapi": "3.0.3",
  "info": {
    "title": "Data Structures API",
    "version": "1.0.0",
    "description": "Following [Advanced Attributes](09.%20Advanced%20Attributes.md), this example\ndemonstrates defining arbitrary data structure to be reused by various\nattribute descriptions.\n\nSince a portion of the `Coupon` data structure is shared between the `Coupon`\ndefinition itself and the `Create a Coupon` action, it was separated into a\n`Coupon Base` data structure in the `Data Structures` API Blueprint Section.\nDoing so enables us to reuse it as a base-type of other attribute definitions.\n\n## API Blueprint\n\n+ [Previous: Advanced Attributes](09.%20Advanced%20Attributes.md)\n\n+ [This: Raw API Blueprint](https://raw.github.com/apiaryio/api-blueprint/master/examples/10.%20Data%20Structures.md)\n\n+ [Next: Resource Model](11.%20Resource%20Model.md)"
  },
  "paths": {
    "/coupons/{id}": {
      "get": {
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "percent_off": {
                      "type": "number",
                      "description": "A positive integer between 1 and 100 that represents the discount the coupon will apply."
                    },
                    "redeem_by": {
                      "type": "number",
                      "description": "Date after which the coupon can no longer be redeemed"
                    },
                    "id": {
                      "type": "string"
                    },
                    "created": {
                      "type": "number",
                      "description": "Time stamp"
                    }
                  },
                  "required": [
                    "id"
                  ]
                },
                "example": {
                  "percent_off": 25,
                  "redeem_by": 0,
                  "id": "250FF",
                  "created": 1415203908
                }
              }
            }
          }
        },
        "summary": "Retrieve a Coupon",
        "operationId": "Retrieve a Coupon",
        "description": "Retrieves the coupon with the given ID.",
        "tags": [
          "Coupons"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the desired coupon.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/coupons": {
      "get": {
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {}
                },
                "example": [
                  {
                    "percent_off": 25,
                    "redeem_by": 0,
                    "id": "250FF",
                    "created": 1415203908
                  }
                ]
              }
            }
          }
        },
        "summary": "List all Coupons",
        "operationId": "List all Coupons",
        "description": "Returns a list of your coupons.",
        "tags": [
          "Coupons"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "A limit on the number of objects to be returned. Limit can range\nbetween 1 and 100 items.",
            "schema": {
              "type": "number",
              "default": 10
            }
          }
        ]
      },
      "post": {
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "percent_off": {
                      "type": "number",
                      "description": "A positive integer between 1 and 100 that represents the discount the coupon will apply."
                    },
                    "redeem_by": {
                      "type": "number",
                      "description": "Date after which the coupon can no longer be redeemed"
                    },
                    "id": {
                      "type": "string"
                    },
                    "created": {
                      "type": "number",
                      "description": "Time stamp"
                    }
                  },
                  "required": [
                    "id"
                  ]
                },
                "example": {
                  "percent_off": 25,
                  "redeem_by": 0,
                  "id": "250FF",
                  "created": 1415203908
                }
              }
            }
          }
        },
        "summary": "Create a Coupon",
        "operationId": "Create a Coupon",
        "description": "Creates a new Coupon.",
        "tags": [
          "Coupons"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "percent_off": 25,
                "redeem_by": 0
              },
              "schema": {
                "type": "object",
                "properties": {
                  "percent_off": {
                    "type": "number",
                    "description": "A positive integer between 1 and 100 that represents the discount the coupon will apply.",
                    "example": 25
                  },
                  "redeem_by": {
                    "type": "number",
                    "description": "Date after which the coupon can no longer be redeemed"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Coupon": {
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "type": "string",
            "example": "250FF"
          },
          "created": {
            "type": "number",
            "example": 1415203908,
            "description": "Time stamp"
          },
          "percent_off": {
            "type": "number",
            "description": "A positive integer between 1 and 100 that represents the discount the coupon will apply.",
            "example": 25
          },
          "redeem_by": {
            "type": "number",
            "description": "Date after which the coupon can no longer be redeemed"
          }
        }
      },
      "Coupons": {
        "type": "array",
        "items": {}
      },
      "Coupon Base": {
        "type": "object",
        "properties": {
          "percent_off": {
            "type": "number",
            "example": 25,
            "description": "A positive integer between 1 and 100 that represents the discount the coupon will apply."
          },
          "redeem_by": {
            "type": "number",
            "description": "Date after which the coupon can no longer be redeemed"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Coupons"
    }
  ]
}